# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CheatSheets.zip
subtitle: "Ultimate Cheat for Developers"
description: "Share quick reference and cheat sheet for developers"
keywords: cheat,sheet,cheatsheets,reference,programming,code table,snippets,linux,command,shortcuts,developers
author: CheatSheets.zip
language: en
timezone: ""

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://cheatsheets.zip
root: /
permalink: :name.html
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
#tag_dir: tag
archive_dir: archives
#category_dir: node
#code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "assets/**/*"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 0
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: "date"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
  - ".github"
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: coo

nofollow:
  enable: true
  field: site
  exclude:
    - "exclude1.com"

excerpt:
  depth: 2
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  #  - type: cjh_google_url_submitter
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter

# hexo-server configuration
server:
  # Solve the problem that occasional real-time refresh is invalid and long articles are truncated
  compress: true

# https://github.com/hexojs/hexo-generator-sitemap#options
sitemap:
  path: sitemap.xml
  tags: false
  categories: false

# Markdown-it configuration
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: false
    quotes: "“”‘’"
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: true
    permalinkClass: h-anchor
    permalinkSymbol: "#"
    case: 1
    separator: "-"
